workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: latest
      java: 21
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web assets
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
